version = 0.1
[default.deploy.parameters]
stack_name = "demo-hello-world"
resolve_s3 = true
s3_prefix = "demo-hello-world"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
