server:
  port: 8080

spring:
  application:
    name: orrlane
  main:
    banner-mode: off

logging:
  level:
    org.springframework: DEBUG
    com.amazonaws.serverless: DEBUG

otel:
  service:
    name: orrlane
  exporter:
    otlp:
      endpoint: https://api.honeycomb.io
      protocol: http/protobuf
      headers:
        x-honeycomb-team: ${HONEYCOMB_KEY}

