server:
  port: 8080

spring:
  application:
    name: orrlane
  main:
    banner-mode: off

logging:
  level:
    org.springframework: INFO

otel:
  service:
    name: orrlane
  exporter:
    otlp:
      endpoint: https://api.honeycomb.io
      protocol: http/protobuf
      headers:
        x-honeycomb-team: ${HONEYCOMB_KEY}
